### ISSUE TITLE
Incrementing does not follow semver spec.

### ISSUE THREAD

**Issue by beporter** [fmahnke/shell-semver#1]
An example will illustrate:

``` shell
$ ./increment_version.sh -m 0.0.2  # Expected => 0.1.0
0.1.2  # <= Actual
```

The [semver spec says](http://semver.org/):

> Patch version MUST be reset to 0 when minor version is incremented.
> 
> Patch and minor version MUST be reset to 0 when major version is incremented.

This obviously has implications for the logic in the script. For example, if I request a bump of all three levels:

``` shell
$ ./increment_version.sh -Mmp 1.2.3   # Expected => 2.1.1 (!?)
```

I doubt this is what anyone would want. Perhaps the options should be downward exclusive? So maybe if I request a `M`ajor version bump, the `m` and `p` options get ignored? I honestly don't know, but the current behavior is definitely incorrect. 

Here's a proposed change:

``` shell
if [ ! -z $major ]
then
  ((a[0]++))
  a[1]=0  # <= added
  a[2]=0  # <= added
fi

if [ ! -z $minor ]
then
  ((a[1]++))
  a[2]=0  # <= added
fi

if [ ! -z $patch ]
then
  ((a[2]++))
fi
```

Thanks.

**Comment by fmahnke** [comment]
Thank you very much for that correction. I integrated your changes as is.

I think it would be unusual to bump multiple versions at the same time, but that case behaves as I'd expect now.

**Comment by beporter** [comment]
:+1: :smile:
